graph LR

D1("./dataset.csv")

D1--->SC1N1

subgraph sc1 ["/home/kimjy/ai-provenance/python-inst/scenario/transformed_script1.py"]
    SC1N1("line 16: read('./dataset.csv')")
    SC1N2("line 20: drop('Target')")
    SC1N3("line 21: drop('Name')")
    SC1N4("line 23: pseudonymize")
    SC1N5("line 25: assign('Target')")
    SC1N6("line 27: split")
    SC1N7("line 27: split")
    SC1N8("line 27: split")
    SC1N9("line 27: split")
    SC1N10("line 30: train")
    SC1N1--"x"-->SC1N2
    SC1N2--"x"-->SC1N3
    SC1N3--"x"-->SC1N4
    SC1N1--"y"-->SC1N5
    SC1N4--"x_train"-->SC1N6
    SC1N4--"x_test"-->SC1N7
    SC1N5--"y_train"-->SC1N8
    SC1N5--"y_test"-->SC1N9
end

